# GNU Make project makefile autogenerated by Premake
ifndef config
  config=release64
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release/App_ExampleBrowser
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_ExampleBrowser_gmake_x64_release
  DEFINES   += -DB3_USE_CLEW -DINCLUDE_CLOTH_DEMOS
  INCLUDES  += -I../../src/clew -I../../examples/ExampleBrowser -I../../src -I../../examples/ThirdPartyLibs
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -msse2 -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -m64 -L/usr/lib64 -L../../bin
  LIBS      += ../../bin/libgwen_gmake_x64_release.a ../../bin/libOpenGL_Window_gmake_x64_release.a ../../bin/libBulletSoftBody_gmake_x64_release.a ../../bin/libBulletDynamics_gmake_x64_release.a ../../bin/libBulletCollision_gmake_x64_release.a ../../bin/libLinearMath_gmake_x64_release.a ../../bin/libBullet3Common_gmake_x64_release.a ../../bin/libBullet3OpenCL_clew_gmake_x64_release.a ../../bin/libBullet3Dynamics_gmake_x64_release.a ../../bin/libBullet3Collision_gmake_x64_release.a ../../bin/libBullet3Geometry_gmake_x64_release.a -ldl -lGL -lGLEW -lX11 -lpthread
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../../bin/libgwen_gmake_x64_release.a ../../bin/libOpenGL_Window_gmake_x64_release.a ../../bin/libBulletSoftBody_gmake_x64_release.a ../../bin/libBulletDynamics_gmake_x64_release.a ../../bin/libBulletCollision_gmake_x64_release.a ../../bin/libLinearMath_gmake_x64_release.a ../../bin/libBullet3Common_gmake_x64_release.a ../../bin/libBullet3OpenCL_clew_gmake_x64_release.a ../../bin/libBullet3Dynamics_gmake_x64_release.a ../../bin/libBullet3Collision_gmake_x64_release.a ../../bin/libBullet3Geometry_gmake_x64_release.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/App_ExampleBrowser
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_ExampleBrowser_gmake_x64_debug
  DEFINES   += -D_DEBUG=1 -DB3_USE_CLEW -DINCLUDE_CLOTH_DEMOS
  INCLUDES  += -I../../src/clew -I../../examples/ExampleBrowser -I../../src -I../../examples/ThirdPartyLibs
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m64 -L/usr/lib64 -L../../bin
  LIBS      += ../../bin/libgwen_gmake_x64_debug.a ../../bin/libOpenGL_Window_gmake_x64_debug.a ../../bin/libBulletSoftBody_gmake_x64_debug.a ../../bin/libBulletDynamics_gmake_x64_debug.a ../../bin/libBulletCollision_gmake_x64_debug.a ../../bin/libLinearMath_gmake_x64_debug.a ../../bin/libBullet3Common_gmake_x64_debug.a ../../bin/libBullet3OpenCL_clew_gmake_x64_debug.a ../../bin/libBullet3Dynamics_gmake_x64_debug.a ../../bin/libBullet3Collision_gmake_x64_debug.a ../../bin/libBullet3Geometry_gmake_x64_debug.a -ldl -lGL -lGLEW -lX11 -lpthread
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../../bin/libgwen_gmake_x64_debug.a ../../bin/libOpenGL_Window_gmake_x64_debug.a ../../bin/libBulletSoftBody_gmake_x64_debug.a ../../bin/libBulletDynamics_gmake_x64_debug.a ../../bin/libBulletCollision_gmake_x64_debug.a ../../bin/libLinearMath_gmake_x64_debug.a ../../bin/libBullet3Common_gmake_x64_debug.a ../../bin/libBullet3OpenCL_clew_gmake_x64_debug.a ../../bin/libBullet3Dynamics_gmake_x64_debug.a ../../bin/libBullet3Collision_gmake_x64_debug.a ../../bin/libBullet3Geometry_gmake_x64_debug.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/clew.o \
	$(OBJDIR)/ExampleEntries.o \
	$(OBJDIR)/main.o \
	$(OBJDIR)/GL_ShapeDrawer.o \
	$(OBJDIR)/OpenGLGuiHelper.o \
	$(OBJDIR)/OpenGLExampleBrowser.o \
	$(OBJDIR)/GwenTextureWindow.o \
	$(OBJDIR)/GwenParameterInterface.o \
	$(OBJDIR)/GraphingTexture.o \
	$(OBJDIR)/GwenProfileWindow.o \
	$(OBJDIR)/gwenUserInterface.o \
	$(OBJDIR)/PhysicsClientC_API.o \
	$(OBJDIR)/PhysicsServerExample.o \
	$(OBJDIR)/PhysicsClientExample.o \
	$(OBJDIR)/RobotControlExample.o \
	$(OBJDIR)/PhysicsServer.o \
	$(OBJDIR)/PhysicsClient.o \
	$(OBJDIR)/PosixSharedMemory.o \
	$(OBJDIR)/Win32SharedMemory.o \
	$(OBJDIR)/BasicExample.o \
	$(OBJDIR)/Tutorial.o \
	$(OBJDIR)/Dof6ConstraintTutorial.o \
	$(OBJDIR)/BenchmarkDemo.o \
	$(OBJDIR)/ForkLiftDemo.o \
	$(OBJDIR)/LoadMeshFromCollada.o \
	$(OBJDIR)/ImportColladaSetup.o \
	$(OBJDIR)/LoadMeshFromObj.o \
	$(OBJDIR)/Wavefront2GLInstanceGraphicsShape.o \
	$(OBJDIR)/ImportObjExample.o \
	$(OBJDIR)/SerializeSetup.o \
	$(OBJDIR)/UrdfParser.o \
	$(OBJDIR)/ImportURDFSetup.o \
	$(OBJDIR)/URDF2Bullet.o \
	$(OBJDIR)/MyMultiBodyCreator.o \
	$(OBJDIR)/BulletUrdfImporter.o \
	$(OBJDIR)/urdfStringSplit.o \
	$(OBJDIR)/ROSURDFImporter.o \
	$(OBJDIR)/BspConverter.o \
	$(OBJDIR)/ImportBspExample.o \
	$(OBJDIR)/BspLoader.o \
	$(OBJDIR)/ImportSTLSetup.o \
	$(OBJDIR)/btWorldImporter.o \
	$(OBJDIR)/btBulletWorldImporter.o \
	$(OBJDIR)/bChunk.o \
	$(OBJDIR)/btBulletFile.o \
	$(OBJDIR)/bFile.o \
	$(OBJDIR)/bDNA.o \
	$(OBJDIR)/Planar2D.o \
	$(OBJDIR)/RaytracerSetup.o \
	$(OBJDIR)/TimeSeriesExample.o \
	$(OBJDIR)/CoordinateSystemDemo.o \
	$(OBJDIR)/TimeSeriesFontData.o \
	$(OBJDIR)/RenderInstancingDemo.o \
	$(OBJDIR)/TimeSeriesCanvas.o \
	$(OBJDIR)/VoronoiFractureDemo.o \
	$(OBJDIR)/btConvexConvexMprAlgorithm.o \
	$(OBJDIR)/SoftDemo.o \
	$(OBJDIR)/RollingFrictionDemo.o \
	$(OBJDIR)/btFractureBody.o \
	$(OBJDIR)/btFractureDynamicsWorld.o \
	$(OBJDIR)/FractureDemo.o \
	$(OBJDIR)/MotorDemo.o \
	$(OBJDIR)/TestHingeTorque.o \
	$(OBJDIR)/ConstraintPhysicsSetup.o \
	$(OBJDIR)/Dof6Spring2Setup.o \
	$(OBJDIR)/ConstraintDemo.o \
	$(OBJDIR)/Hinge2Vehicle.o \
	$(OBJDIR)/RaytestDemo.o \
	$(OBJDIR)/MultiDofDemo.o \
	$(OBJDIR)/TestJointTorqueSetup.o \
	$(OBJDIR)/MultiBodyConstraintFeedback.o \
	$(OBJDIR)/InvertedPendulumPDControl.o \
	$(OBJDIR)/stb_image.o \
	$(OBJDIR)/tiny_obj_loader.o \
	$(OBJDIR)/tinyxml.o \
	$(OBJDIR)/tinyxmlparser.o \
	$(OBJDIR)/tinystr.o \
	$(OBJDIR)/tinyxmlerror.o \
	$(OBJDIR)/b3Clock.o \
	$(OBJDIR)/b3ResourcePath.o \
	$(OBJDIR)/GyroscopicSetup.o \
	$(OBJDIR)/pose.o \
	$(OBJDIR)/model.o \
	$(OBJDIR)/link.o \
	$(OBJDIR)/joint.o \
	$(OBJDIR)/printf_console.o \
	$(OBJDIR)/string_split.o \
	$(OBJDIR)/PairBench.o \
	$(OBJDIR)/GpuConvexScene.o \
	$(OBJDIR)/GpuRigidBodyDemo.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking App_ExampleBrowser
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning App_ExampleBrowser
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/clew.o: ../../src/clew/clew.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ExampleEntries.o: ../../examples/ExampleBrowser/ExampleEntries.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/main.o: ../../examples/ExampleBrowser/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GL_ShapeDrawer.o: ../../examples/ExampleBrowser/GL_ShapeDrawer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/OpenGLGuiHelper.o: ../../examples/ExampleBrowser/OpenGLGuiHelper.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/OpenGLExampleBrowser.o: ../../examples/ExampleBrowser/OpenGLExampleBrowser.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GwenTextureWindow.o: ../../examples/ExampleBrowser/GwenGUISupport/GwenTextureWindow.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GwenParameterInterface.o: ../../examples/ExampleBrowser/GwenGUISupport/GwenParameterInterface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GraphingTexture.o: ../../examples/ExampleBrowser/GwenGUISupport/GraphingTexture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GwenProfileWindow.o: ../../examples/ExampleBrowser/GwenGUISupport/GwenProfileWindow.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/gwenUserInterface.o: ../../examples/ExampleBrowser/GwenGUISupport/gwenUserInterface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PhysicsClientC_API.o: ../../examples/SharedMemory/PhysicsClientC_API.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PhysicsServerExample.o: ../../examples/SharedMemory/PhysicsServerExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PhysicsClientExample.o: ../../examples/SharedMemory/PhysicsClientExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RobotControlExample.o: ../../examples/SharedMemory/RobotControlExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PhysicsServer.o: ../../examples/SharedMemory/PhysicsServer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PhysicsClient.o: ../../examples/SharedMemory/PhysicsClient.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PosixSharedMemory.o: ../../examples/SharedMemory/PosixSharedMemory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Win32SharedMemory.o: ../../examples/SharedMemory/Win32SharedMemory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BasicExample.o: ../../examples/BasicDemo/BasicExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Tutorial.o: ../../examples/Tutorial/Tutorial.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Dof6ConstraintTutorial.o: ../../examples/Tutorial/Dof6ConstraintTutorial.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BenchmarkDemo.o: ../../examples/Benchmarks/BenchmarkDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ForkLiftDemo.o: ../../examples/ForkLift/ForkLiftDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoadMeshFromCollada.o: ../../examples/Importers/ImportColladaDemo/LoadMeshFromCollada.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ImportColladaSetup.o: ../../examples/Importers/ImportColladaDemo/ImportColladaSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoadMeshFromObj.o: ../../examples/Importers/ImportObjDemo/LoadMeshFromObj.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Wavefront2GLInstanceGraphicsShape.o: ../../examples/Importers/ImportObjDemo/Wavefront2GLInstanceGraphicsShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ImportObjExample.o: ../../examples/Importers/ImportObjDemo/ImportObjExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SerializeSetup.o: ../../examples/Importers/ImportBullet/SerializeSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/UrdfParser.o: ../../examples/Importers/ImportURDFDemo/UrdfParser.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ImportURDFSetup.o: ../../examples/Importers/ImportURDFDemo/ImportURDFSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/URDF2Bullet.o: ../../examples/Importers/ImportURDFDemo/URDF2Bullet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MyMultiBodyCreator.o: ../../examples/Importers/ImportURDFDemo/MyMultiBodyCreator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BulletUrdfImporter.o: ../../examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/urdfStringSplit.o: ../../examples/Importers/ImportURDFDemo/urdfStringSplit.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ROSURDFImporter.o: ../../examples/Importers/ImportURDFDemo/ROSURDFImporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BspConverter.o: ../../examples/Importers/ImportBsp/BspConverter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ImportBspExample.o: ../../examples/Importers/ImportBsp/ImportBspExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BspLoader.o: ../../examples/Importers/ImportBsp/BspLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ImportSTLSetup.o: ../../examples/Importers/ImportSTLDemo/ImportSTLSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/btWorldImporter.o: ../../Extras/Serialize/BulletWorldImporter/btWorldImporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/btBulletWorldImporter.o: ../../Extras/Serialize/BulletWorldImporter/btBulletWorldImporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/bChunk.o: ../../Extras/Serialize/BulletFileLoader/bChunk.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/btBulletFile.o: ../../Extras/Serialize/BulletFileLoader/btBulletFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/bFile.o: ../../Extras/Serialize/BulletFileLoader/bFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/bDNA.o: ../../Extras/Serialize/BulletFileLoader/bDNA.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Planar2D.o: ../../examples/Planar2D/Planar2D.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RaytracerSetup.o: ../../examples/RenderingExamples/RaytracerSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TimeSeriesExample.o: ../../examples/RenderingExamples/TimeSeriesExample.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CoordinateSystemDemo.o: ../../examples/RenderingExamples/CoordinateSystemDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TimeSeriesFontData.o: ../../examples/RenderingExamples/TimeSeriesFontData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RenderInstancingDemo.o: ../../examples/RenderingExamples/RenderInstancingDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TimeSeriesCanvas.o: ../../examples/RenderingExamples/TimeSeriesCanvas.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VoronoiFractureDemo.o: ../../examples/VoronoiFracture/VoronoiFractureDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/btConvexConvexMprAlgorithm.o: ../../examples/VoronoiFracture/btConvexConvexMprAlgorithm.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SoftDemo.o: ../../examples/SoftDemo/SoftDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RollingFrictionDemo.o: ../../examples/RollingFrictionDemo/RollingFrictionDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/btFractureBody.o: ../../examples/FractureDemo/btFractureBody.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/btFractureDynamicsWorld.o: ../../examples/FractureDemo/btFractureDynamicsWorld.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FractureDemo.o: ../../examples/FractureDemo/FractureDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MotorDemo.o: ../../examples/DynamicControlDemo/MotorDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TestHingeTorque.o: ../../examples/Constraints/TestHingeTorque.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ConstraintPhysicsSetup.o: ../../examples/Constraints/ConstraintPhysicsSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Dof6Spring2Setup.o: ../../examples/Constraints/Dof6Spring2Setup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ConstraintDemo.o: ../../examples/Constraints/ConstraintDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Hinge2Vehicle.o: ../../examples/Vehicles/Hinge2Vehicle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RaytestDemo.o: ../../examples/Raycast/RaytestDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MultiDofDemo.o: ../../examples/MultiBody/MultiDofDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TestJointTorqueSetup.o: ../../examples/MultiBody/TestJointTorqueSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MultiBodyConstraintFeedback.o: ../../examples/MultiBody/MultiBodyConstraintFeedback.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/InvertedPendulumPDControl.o: ../../examples/MultiBody/InvertedPendulumPDControl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/stb_image.o: ../../examples/ThirdPartyLibs/stb_image/stb_image.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/tiny_obj_loader.o: ../../examples/ThirdPartyLibs/Wavefront/tiny_obj_loader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/tinyxml.o: ../../examples/ThirdPartyLibs/tinyxml/tinyxml.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/tinyxmlparser.o: ../../examples/ThirdPartyLibs/tinyxml/tinyxmlparser.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/tinystr.o: ../../examples/ThirdPartyLibs/tinyxml/tinystr.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/tinyxmlerror.o: ../../examples/ThirdPartyLibs/tinyxml/tinyxmlerror.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/b3Clock.o: ../../examples/Utils/b3Clock.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/b3ResourcePath.o: ../../examples/Utils/b3ResourcePath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GyroscopicSetup.o: ../../examples/GyroscopicDemo/GyroscopicSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/pose.o: ../../examples/ThirdPartyLibs/urdf/urdfdom/urdf_parser/src/pose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/model.o: ../../examples/ThirdPartyLibs/urdf/urdfdom/urdf_parser/src/model.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/link.o: ../../examples/ThirdPartyLibs/urdf/urdfdom/urdf_parser/src/link.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/joint.o: ../../examples/ThirdPartyLibs/urdf/urdfdom/urdf_parser/src/joint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/printf_console.o: ../../examples/ThirdPartyLibs/urdf/boost_replacement/printf_console.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/string_split.o: ../../examples/ThirdPartyLibs/urdf/boost_replacement/string_split.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PairBench.o: ../../examples/OpenCL/broadphase/PairBench.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GpuConvexScene.o: ../../examples/OpenCL/rigidbody/GpuConvexScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GpuRigidBodyDemo.o: ../../examples/OpenCL/rigidbody/GpuRigidBodyDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
